// <auto-generated />
namespace StudentStudyProgram.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CleanStart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CleanStart));
        
        string IMigrationMetadata.Id
        {
            get { return "202512231641252_CleanStart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
